version: '3'

services:
  mongodb:
    build:
      context: ./mongodb
      dockerfile: Dockerfile
      args:
        - mongodb_username=${MONGODB_USERNAME}
        - mongodb_password=${MONGODB_PASSWORD}
        - mongodb_initdb_database=${MONGO_INITDB_DATABASE}
    volumes:
      - mongodata:/data/db:rw
    ports:
      - "27018:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=adminpass
    env_file:
      - .env

volumes:
  mongodata: