version: '3'

services:
  database:
    container_name: promobit_mysql
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
    ports:
      - "${DATABASE_PORT}:3306"
    volumes:
      - database-data:/var/lib/mysql

  mongodb:
    container_name: promobit_mongodb
    build:
      context: ./mongodb
      dockerfile: Dockerfile
      args:
        - mongodb_username=${MONGODB_USERNAME}
        - mongodb_password=${MONGODB_PASSWORD}
        - mongodb_initdb_database=${MONGO_INITDB_DATABASE}
    volumes:
      - mongo-data:/data/db:rw
    ports:
      - "${MONGODB_PORT}:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
    env_file:
      - .env

  rabbitmq:
    container_name: promobit_rabbitmq
    image: rabbitmq:management
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    ports:
      - "${RABBITMQ_PORT}:5672"
      - "${RABBITMQ_MANAGER_PORT}:15672"
    restart: unless-stopped
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

  redis:
    container_name: promobit_redis
    image: redis:alpine
    ports:
      - "${REDIS_PORT}:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD}

  php:
    container_name: promobit_php
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./src:/app
    env_file:
      - .env
    depends_on:
      - database
      - mongodb
      - rabbitmq
      - redis

volumes:
  database-data:
  mongo-data:
  rabbitmq-data: