framework:
    cache:

        app: cache.adapter.redis
        default_redis_provider: '%env(REDIS_DSN)%'

        pools:
            cache.my_redis:
                adapter: cache.adapter.redis
                default_lifetime: 60
            #my.dedicated.cache: null
