doctrine_mongodb:
    auto_generate_proxy_classes: true
    auto_generate_hydrator_classes: true
    connections:
        default:
            # server: '%env(MONGODB_URL)%'
            server: "%mongodb_server%"
            options:
                # username: '%env(MONGODB_USERNAME)%'
                # password: '%env(MONGODB_PASSWORD)%'
                # authSource: '%env(MONGO_INITDB_DATABASE)%'
    # default_database: test_database
    default_database: '%env(MONGODB_DB)%'
    document_managers:
        default:
            auto_mapping: true
            mappings:
                App:
                    is_bundle: false
                    type: annotation
                    dir: '%kernel.project_dir%/src/Document'
                    prefix: 'App\Document'
                    alias: App
